config/routes.rb
Slyde2::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :decks

  match 'in/:random' => 'decks#show'

  

  root :to => "home#index"

end

app/models/deck.rb
class Deck < ActiveRecord::Base
	# Look up how to do this. Initialize the value to zero instead of in model
	#before_initialize :init
	
  validates_presence_of :random
  validates_uniqueness_of :random

  before_save :clean_filename
  
  belongs_to :user
	
	def init
		viewcount = 0
	end
	
	# Devise
	def self.visible_by(user)
	  if user.is_admin
		Deck.all
	  else
	    Deck.where :user_id => user.id
	  end
	end

	# Paperclip
  has_attached_file :doc,
					#:styles => { :thumb => ["100x100#", :png] },
					#Previous URL format before trying random
					#:url => "/in/:id/:basename.:extension",
					:url => "/in/:id/:random",
					:path => ":rails_root/public/in/:id/:basename.:extension",
					:storage => :s3,
					:bucket => 'Slyde',
					:s3_credentials => {
					  :access_key_id     => 'AKIAJETT5WWWOMFUITCQ',
					  :secret_access_key => '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'
					}
					
  #Amazon s3 Access
  #AWS::S3::Base.establish_connection!(
  #:access_key_id     => 'AKIAJETT5WWWOMFUITCQ',
  #:secret_access_key => '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'
  #)


	
# The below was supposed to make scribd_fu work, but might be only rails 2, but works when scribd is local
  has_ipaper_and_uses 'Paperclip' 
  

#  To create a unique ID
  protected
  def before_validation
    self.random = rand(36**8).to_s(36) if self.new_record? and self.random.nil?
  end 
  #note: Rails has this built in SecureRandom.hex(4) => makes an 8 digit random hex

  def clean_filename
     doc_file_name.gsub!(' ', '_')
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from ActionController::RoutingError, :with => :error_msg
  rescue_from NoMethodError, :with => :error_msg
  
  private
  def error_msg
    flash[:error] = "Sorry, can't do that!"
	redirect_to :root
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

include ActionView::Helpers::SanitizeHelper


  # GET /decks
  # GET /decks.xml
  def index
  #  This is the default
  #  @decks = Deck.all

  #  redefined for User control
    @decks = Deck.visible_by(current_user)
	
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.xml
  def show
	
	if params[:random]
		then
		@deck = Deck.find_by_random(params[:random])
		else
		@deck = Deck.find(params[:id])
	end

	@deck.viewcount += 1
	@deck.save
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.xml
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end

  
  # POST /decks
  # POST /decks.xml

  def create
	
	
	#for Paperclip
	@deck = Deck.create(params[:deck])
	@deck.viewcount = 0
	
	#for Devise
	if user_signed_in?
	@deck.user_id = current_user.id
	end
	
	#@deck = Deck.new(params[:deck])
	
    respond_to do |format|
      if @deck.save
        format.html { redirect_to root_path, :deck_id => @deck.id, 
		# This used to just say @deck, changed for ajax
		:notice => sanitize("Your deck can be viewed at <a href='#{root_url}in/#{@deck.random}'>#{root_url}in/#{@deck.random} </a>" ) }
		  
		#:notice => "Your deck can be viewed at http://slyde.it/in/#{@deck.random}" } 
		  
  		#This is part of the ajax call
		#format.js
		
        format.xml  { render :xml => @deck, :status => :created, :location => @deck }
      else
        format.html  { render :action => "new" }
        format.xml  { render :xml => @deck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.xml
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to(@deck, :notice => 'Deck was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.xml
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to(decks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  #Trying to get the ajax to work
  #@deck = Deck.find(params[:id])
  #	  if !params[:deck_id].nil?
  #	    #flash[:notice] =
  #		puts 'Deck_id not nil home#index'
  #	  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/decks/_deck.html.erb
<% unless @deck.nil? %>
<tr>
<td>http://slyde.it/in/<%= deck.random %></td>
TESTING DECK PARTIAL
</tr>
<% end %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<%= image_tag 'Slyde_logo.png', :width => "300px"%>
<br>
<br>
<h1>Editing deck</h1>

<%= render 'form' %>

<h2>Attach Deck with Paperclip</h2>
<% form_for :deck, @deck, :url => decks_path, :html => { :multipart => true } do |form| %>
  
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" %>
<% end %>


<%= link_to 'Show', @deck %> |
<%#= link_to 'Back', decks_path %> |
<%= link_to 'Home', root_path %>

app/views/decks/index.html.erb
<%= image_tag 'Slyde_logo.png', :width => "300px"%>
<br>
<br>
<h1>Listing decks</h1>

<table>
  <tr>
    <th></th>
	<th>ID</th>
    <th>File Name</th>
    <th>Views</th>
	<th>URL</th>
	<th></th>
	<th></th>
  </tr>

<% @decks.each do |deck| %>
  <tr>
    <td><%#= deck.name %></td>
	<td>Deck ID <%= deck.id %></td>
	<td><%= deck.doc_file_name %></td>
	<td><%= deck.viewcount %> views</td>
	<td>http://slyde.it/in/<%= deck.random %></td>
	<td><%#= deck.ipaper_id %></td>
	<td><%#= deck.ipaper_access_key %></td>	
	<td><%#= deck.doc_file_size %></td>
	
    <td><%= link_to 'View', deck %></td>
    <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
    <td><%= link_to 'Kill', deck, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deck', new_deck_path %> |
<%= link_to 'Home', root_path %>

app/views/decks/new.html.erb
<%= image_tag 'Slyde_logo.png', :width => "300px"%>
<br>
<br>
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %> |
<%= link_to 'Home', root_path %>

app/views/decks/show.html.erb
<%= image_tag 'Slyde_logo.png', :width => "100px"%>
<br>
<br>
<p id="notice"><%= notice %></p>

  <%= raw @deck.display_ipaper %>
  
<%= link_to 'Back', decks_path %> |
<%= link_to 'Home', root_path %>

app/views/home/_random.html.erb
<% unless @deck.nil? %>
<tr>
<td>http://slyde.it/in/<%= deck.random %></td>
TESTING RANDOM PARTIAL
</tr>
<% end %>

app/views/home/index.html.erb
<center><%= image_tag 'Slyde_logo.png', :width => "400px"%>

<h2>
Share slides without sharing files.
</h2>
<br>
Upload a file below and share the link with anyone you'd like. 
<br>
They can view the slides, but can't download it.
<br><br><br><br>
	<%#= render 'form' %>

	<% form_for :deck, @deck, :url => decks_path, :html => { :multipart => true } do |form| %>
	  <%= form.file_field :doc, :class => 'input_style' %>
	  <%= submit_tag value="Submit", :class => 'btn' %>
	  
	<% end %>
<br>
<br>
	<div id="deck">
<% unless @deck.nil? %>
	INITIAL URL TEXT TEST
	<%#= render 'deck' %>
	
<% end %>
	</div>
	
</center>
<br>
<br>

<% if user_signed_in? %><%= link_to 'My Decks', decks_path %> <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slyde it. Don't share it.</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>
<center>
	<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
	<% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
	<% end %>
	<% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
	<% end %>
	
</center>
<br>
<ul class="hmenu">
  <%= render 'devise/registration_items' %>
  <%= render 'devise/login_items' %>
</ul>
</body>
</html>